server:
  port: 7000
spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 10.202.203.55:8848
    gateway:
      discovery:
        locator:
          enabled: true # 让gateway可以发现nacos中的微服务
      routes:
        - id: product_route
          uri: lb://service-product # lb指的是从nacos中按照名称获取微服务,并遵循负载均衡策略
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1
        - id: oauth_route
          uri: lb://service-oauth
          predicates:
            - Path=/oauth/**
        - id: order_route
          uri: lb://service-order
          predicates:
            - Path=/order-gateway/**
          filters:
            - StripPrefix=1
  zipkin:
    base-url: http://10.202.203.55:9411 #zipkin server的请求地址
#    discoveryClientEnabled: false #让nacos把它当成一个URL，而不要当做服务名
  sleuth:
    sampler:
      probability: 1.0 #采样的百分比
